name: genesapp
description: "A new Flutter project."

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^3.12.1  # Mover esta línea aquí, al nivel adecuado
  firebase_auth: ^5.5.1
  cloud_firestore: ^5.6.5
  google_sign_in: ^6.3.0
  cupertino_icons: ^1.0.8
  flutter_signin_button: ^2.0.0
  permission_handler: ^11.4.0
  file_picker: ^9.2.1
  firebase_storage: ^12.4.4
  http: ^1.3.0
  path: ^1.9.1
  animate_do: ^4.2.0
  url_launcher: ^6.3.1
  syncfusion_flutter_pdfviewer: ^28.2.12

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/genesappLogo-removebg-preview.png
